{
 "title": "Currency Service",
 "refresh": "10s",
 "panels": [
  {
   "title": "Conversions To DKK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "currency_converted_to_dkk_total"
    }
   ]
  },
  {
   "title": "Conversions From DKK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "currency_converted_from_dkk_total"
    }
   ]
  },
  {
   "title": "Exchange Rate Updates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "currency_exchange_rate_updates_total"
    }
   ]
  },
  {
   "title": "Failed Exchange Updates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "currency_exchange_rate_update_failures_total"
    }
   ]
  },
  {
   "title": "Conversions To DKK (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(currency_converted_to_dkk_total[1m])"
    }
   ]
  },
  {
   "title": "Conversions From DKK (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(currency_converted_from_dkk_total[1m])"
    }
   ]
  }
 ]
}