{
 "title": "Ledger Service",
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_total_requests{job=\"gringotts\",instance=\"ledgerservice:8080\"}",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Request Duration (Histogram avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(microsoft_aspnetcore_hosting_http_server_request_duration_sum{job=\"gringotts\",instance=\"ledgerservice:8080\"}[1m]) / rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"gringotts\",instance=\"ledgerservice:8080\"}[1m])",
     "legendFormat": "Avg Duration (s)"
    }
   ]
  },
  {
   "title": ".NET GC Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "system_runtime_gc_heap_size{job=\"gringotts\",instance=\"ledgerservice:8080\"}",
     "legendFormat": "GC Heap"
    }
   ]
  }
 ]
}