{
 "title": "Transaction Consumer",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Messages Consumed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "transaction_consumer_messages_total",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Message Processing Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(transaction_consumer_processing_duration_seconds_sum[1m]) / rate(transaction_consumer_processing_duration_seconds_count[1m])",
     "legendFormat": "Avg Duration (s)"
    }
   ]
  },
  {
   "title": ".NET GC Heap Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "system_runtime_gc_heap_size{job=\"gringotts\",instance=\"transactionconsumer:8080\"}",
     "legendFormat": "GC Heap"
    }
   ]
  },
  {
   "title": "Total Memory Allocated (.NET)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"gringotts\",instance=\"transactionconsumer:8080\"}",
     "legendFormat": "Memory"
    }
   ]
  }
 ]
}