{
 "title": "Transaction Publisher",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_total_requests{job=\"gringotts\",instance=\"transactionpublisher:8080\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(microsoft_aspnetcore_hosting_http_server_request_duration_sum{job=\"gringotts\",instance=\"transactionpublisher:8080\"}[1m]) / rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"gringotts\",instance=\"transactionpublisher:8080\"}[1m])",
     "legendFormat": "Avg Duration (s)"
    }
   ]
  },
  {
   "title": ".NET GC Heap Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "system_runtime_gc_heap_size{job=\"gringotts\",instance=\"transactionpublisher:8080\"}",
     "legendFormat": "GC Heap"
    }
   ]
  },
  {
   "title": "Total Memory Allocated (.NET)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"gringotts\",instance=\"transactionpublisher:8080\"}",
     "legendFormat": "Memory"
    }
   ]
  }
 ]
}