global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gringotts'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'transactionpublisher:8080'
          - 'ledgerservice:8080'
          - 'apigateway:8080'
          - 'transactionconsumer:8080'
          - 'currencyservice:8080'
