name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      IMAGE_PREFIX: roharx/gringotts-deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Version
        id: version
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Generated version: $VERSION"

      - name: Build and push migrations
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Gringotts.Migration/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}:migration-${{ env.VERSION }}
            ${{ env.IMAGE_PREFIX }}:migration-latest

      - name: Build and push apigateway
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Gringotts.ApiGateway/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}:apigateway-${{ env.VERSION }}
            ${{ env.IMAGE_PREFIX }}:apigateway-latest

      - name: Build and push currencyservice
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Gringotts.CurrencyService/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}:currencyservice-${{ env.VERSION }}
            ${{ env.IMAGE_PREFIX }}:currencyservice-latest

      - name: Build and push ledgerservice
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Gringotts.LedgerService/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}:ledgerservice-${{ env.VERSION }}
            ${{ env.IMAGE_PREFIX }}:ledgerservice-latest

      - name: Build and push transactionpublisher
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Gringotts.TransactionPublisher/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}:transactionpublisher-${{ env.VERSION }}
            ${{ env.IMAGE_PREFIX }}:transactionpublisher-latest

      - name: Build and push transactionconsumer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Gringotts.TransactionConsumer/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}:transactionconsumer-${{ env.VERSION }}
            ${{ env.IMAGE_PREFIX }}:transactionconsumer-latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./src/Gringotts.Frontend/gringotts-frontend
          file: ./src/Gringotts.Frontend/gringotts-frontend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}:frontend-${{ env.VERSION }}
            ${{ env.IMAGE_PREFIX }}:frontend-latest
