name: Build & Push All Services to gringotts-deployment

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_REPO: roharx/gringotts-deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: apigateway
            context: .
            dockerfile: src/Gringotts.ApiGateway/Dockerfile

          - service: transactionpublisher
            context: .
            dockerfile: src/Gringotts.TransactionPublisher/Dockerfile

          - service: transactionconsumer
            context: .
            dockerfile: src/Gringotts.TransactionConsumer/Dockerfile

          - service: currencyservice
            context: .
            dockerfile: src/Gringotts.CurrencyService/Dockerfile

          - service: ledgerservice
            context: .
            dockerfile: src/Gringotts.LedgerService/Dockerfile

          - service: frontend
            context: ./src/Gringotts.Frontend/gringotts-frontend
            dockerfile: Dockerfile

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ matrix.service }}-latest
            ${{ env.DOCKERHUB_REPO }}:${{ matrix.service }}-${{ github.sha }}
