name: Build & Push Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_NAMESPACE: roharx

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: apigateway
            context: .
            dockerfile: src/Gringotts.ApiGateway/Dockerfile
          - name: transactionpublisher
            context: .
            dockerfile: src/Gringotts.TransactionPublisher/Dockerfile
          - name: transactionconsumer
            context: .
            dockerfile: src/Gringotts.TransactionConsumer/Dockerfile
          - name: currencyservice
            context: .
            dockerfile: src/Gringotts.CurrencyService/Dockerfile
          - name: ledgerservice
            context: .
            dockerfile: src/Gringotts.LedgerService/Dockerfile
          - name: frontend
            context: ./src/Gringotts.Frontend/gringotts-frontend
            dockerfile: Dockerfile

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push ${{ matrix.name }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_NAMESPACE }}/gringotts-${{ matrix.name }}:latest
            ${{ env.DOCKERHUB_NAMESPACE }}/gringotts-${{ matrix.name }}:${{ github.sha }}
